global using UnityEngine;
global using Modding;
global using Vasi;
global using USceneManager = UnityEngine.SceneManagement.SceneManager;
global using UnityEngine.SceneManagement;
global using UObject = UnityEngine.Object;
global using HutongGames.PlayMaker;
global using HutongGames.PlayMaker.Actions;
global using URandom = UnityEngine.Random;
global using System.Reflection;
global using VEnum = Vasi.EnumerableUtil;
